USE WAREHOUSE dev_wh;
USE DATABASE portfolio_db;
USE SCHEMA raw;

CREATE OR REPLACE FILE FORMAT csv_format
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1;

CREATE OR REPLACE FILE FORMAT parquet_format
  TYPE = PARQUET;